FROM fluent/fluentd:v1.16-debian-1
USER root
RUN apt-get update && \
    apt-get install -y \
        curl \
        net-tools \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.3.0"]
USER fluent
