FROM fluent/fluentd:v1.16.3-2.0
USER root

RUN mkdir -p /fluentd/etc /fluentd/plugins

COPY ./fluentd.conf /fluentd/etc/


RUN apt-get update && \
    apt-get install -y net-tools && \
    gem install faraday-net_http -v 3.0.2 && \
    gem install faraday -v 2.8.1 && \
    fluent-gem install fluent-plugin-elasticsearch 


USER fluent

EXPOSE 24224

CMD ["fluentd", "-c", "/fluentd/etc/fluentd.conf", "-p", "/fluentd/plugins"]
