version: '3.8'

volumes:
  web-conf:
  load-balancer-conf:
  fluentd-conf:
  elasticsearch-conf:
  kibana-conf:
  web-logs:
  elasticsearch-data:
  logstash-conf:

services:
  web:
    build: ./app
    volumes:
      - ./web:/usr/share/nginx/html
      - web-conf:/etc/nginx
      - web-logs:/var/log/nginx
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - load-balancer-conf:/etc/load-balancer
    ports:
      - "80:80"
    depends_on:
      - web

  fluentd:
    build: ./fluentd
    volumes:
      - web-logs:/var/log/nginx
      - fluentd-conf:/fluentd/etc  
    depends_on:
      - web
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300


  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    volumes:
      - kibana-conf:/usr/share/kibana/config  
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    user: root
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro # Chemin relatif pour les fichiers de pipeline
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=test123
      - ELASTIC_HOST=http://elasticsearch:9200
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
