version: '3'

services:
  app1:
    image: projet_web:latest

    

  app2:
    image: projet_web:latest

    

  load_balancer:
    image: projet_load_balancer:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

  fluentd:
    image: fluent:latest
    volumes:
      - ./logging/fluentd.conf:/fluentd/etc/fluentd.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

networks:
  default:
    external: true
    name: projetdocker_default