version: '3'

services:
  app1:
    image: projet_web:latest
    build: ./app
    volumes:
      - app1_logs:/app/logs
    

  app2:
    image: projet_web:latest
    build: ./app
    volumes:
      - app2_logs:/app/logs
    

  load_balancer:
    image: projet_load_balancer:latest
    build: ./load_balancer
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

  fluentd:
    image: fluent/fluentd:v1.16.3-2.0
    volumes:
      - ./logging/fluentd.conf:/fluentd/etc/fluentd.conf
      - fluentd_conf:/fluentd/etc
      - fluentd_logs:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

networks:
  default:
    external: true
    name: projetdocker_default

volumes:
  app1_logs:
  app2_logs:
  fluentd_conf:
  fluentd_logs:
