version: '3.8'

volumes:
  web-conf:
  load-balancer-conf:
  fluentd-conf:
  elasticsearch-conf:
  kibana-conf:
  web-logs:
  elasticsearch-data:

services:
  web:
    build: ./app
    volumes:
      - ./web:/usr/share/nginx/html
      - web-conf:/etc/nginx
      - web-logs:/var/log/nginx
    networks:
      - webnet
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - load-balancer-conf:/etc/load-balancer
    networks:
      - webnet
    ports:
      - "80:80"
    depends_on:
      - web

  fluentd:
    image: fluent/fluentd:v1.14-1
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
      - web-logs:/var/log/nginx
      - elasticsearch-conf:/usr/share/elasticsearch/config
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - webnet
      - elasticsearch-net
    depends_on:
      - web
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    volumes:
      - kibana-conf:/usr/share/kibana/config
    restart: always
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    networks:
      - elasticsearch-net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  webnet:
  elasticsearch-net:
    driver: bridge
